coverage:
  range: 70...100
ignore:
  - "nes_test"
  - "nes_ui_base"
  - "nes_ui_sfml"
  - "nes_ui_gtk"
  - "nes_ui_tui"
  - "nes_ui_native_windows"
  - "tests.rs"
  - "**/tests.rs"
  - "tests"
  - "**/tests"
