[workspace]
members = [
    "apu2a03",
    "cartridge",
    "common",
    "controller",
    "cpu6502",
    "display",
    "nes_test", # This is for my testing and playing the games, a mess for now
    "nes_tester", # This is for unit testing (headless)
    "ppu2c02",
]
