[package]
name = "cpu6502"
version = "0.1.0"
authors = ["Amjad Alsharafi <amjadsharafi10@gmail.com>"]
edition = "2018"


[dependencies]
common = { path = "../common" }

# for testing only
[dev-dependencies]
nes_tester = { path = "../nes_tester" }
