name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  linux:

    runs-on: ubuntu-20.04

    steps:
    - name: Download apt packages
      run: |
        sudo apt-get update -y && sudo apt-get install -y libsfml-dev libcsfml-dev libasound2-dev libgtk-3-dev libatk1.0-dev libpango1.0-dev libudev-dev

    - name: Install cargo-tarpaulin
      uses: actions-rs/install@v0.1
      with:
        crate: cargo-tarpaulin
        version: latest
        use-tool-cache: true

    - uses: actions/checkout@v2

    - uses: actions-rs/audit-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build
      run: cargo build --verbose

    - name: Run test cargo-tarpaulin
      run: cargo tarpaulin -t 300 --workspace -e nes_ui_native_windows nes_ui_sfml nes_ui_gtk nes_ui_tui -v -o Xml

    - uses: codecov/codecov-action@v1.0.11

      # For some reason windows crashes when running the emulator tests
      #windows:
      #  runs-on: windows-latest
      #  
      #  steps:
      #    - uses: actions/checkout@v2
      #    - name: Build native windows UI
      #      run: cargo build -p nes_ui_native_windows --verbose
      #    - name: Run tests
      #      run: cargo test --workspace --exclude nes_ui_gtk --exclude nes_ui_sfml --lib
