name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: download apt packages
      run: |
        sudo apt-get update -y && sudo apt-get install -y libsfml-dev libcsfml-dev libasound2-dev
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - uses: actions-rs/tarpaulin@v0.1.0
    - uses: codecov/codecov-action@v1.0.11
