name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Download apt packages
      run: |
        sudo apt-get update -y && sudo apt-get install -y libsfml-dev libcsfml-dev libasound2-dev libgtk-3-dev libatk1.0-dev libpango1.0-dev libudev-dev
    - name: Install cargo-tarpaulin
      uses: actions-rs/install@v0.1
      with:
        crate: cargo-tarpaulin
        version: latest
        use-tool-cache: true
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
  # - name: Run tests
  #   run: cargo test --verbose
    - name: Run test cargo-tarpaulin
      run: cargo tarpaulin --workspace -e nes_test nes_ui_base nes_sfml nes_gtk nes_tui -v -o Xml
    - uses: codecov/codecov-action@v1.0.11
